name: Test

on:
  push:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm run badges

      - name: Report coverage
        uses: romeovs/lcov-reporter-action@v0.2.19
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info

      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: github.ref == 'refs/heads/master'
        with:
          branch: docs
          folder: docs
