name: Publish development release

on:
  workflow_dispatch:

jobs:
  publish_dev_release:
    name: Publish development release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --tag=dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
